update from NMRlipids orig repo fork (#3)
* Add orange and incomplete ulmschneider mapping file

* Update refs.bib

I Re-uploaded the Zenodo record of https://zenodo.org/record/17208 as https://zenodo.org/record/46152 which also now includes the ".tpr" file. I fixed the corresponding reference to direct to the new link and commented the old one.

* Fix typo in table and update new reference by Jukka to pdf

* Calculating OP-change versus Bound cation charge.

* Add link to todo comment

* add BERGERdppc_0na402.tpr

* add

* Current versions of analysis and l

* Data files for plotting

* Gnuplot scripts for plotting

* add ulm0na402.tpr

* add ./ulm12na402.tpr ./ulm77na402.tpr

* Fix typo in EXP-Altenbach1984-T313K.dat

* added electrometer reference to the abstract

* Scripts.

* Data files.

* Needed for key.

* Update dOP_vs_boundCationCharge_P.pdf

* update text

* temporary updates

* Temporary updates

* temporary updates

* Add order parameter results from long simulations by Matti

* Add density results from longer runs

* Updates

* added data for DPPC , Slipids , 350-1000mM NaCl conc. + modified scripts

* updates

* Updates

* Updates

* added data for CHARMM36_no-NBFIX, 350mM NaCl, Roux param, full charge + modified scripts

* Updating from the original NMRlipids repo (#1)

* Scripts.

* Data files.

* Needed for key.

* Update dOP_vs_boundCationCharge_P.pdf

* update text

* temporary updates

* Temporary updates

* temporary updates

* Add order parameter results from long simulations by Matti

* Add density results from longer runs

* Updates

* updates

* Updates

* Updates

* Add new results by Melcr

* Fix NAdensities.eps

* Update discussion and add author

* Add CHARMM results with new CaCl_2 model by Claire Loison http://nmrlipids.blogspot.com/2015/12/towards-submission-of-nmrlipids-ii.html?showComment=1463482818700#c8756317300169938071

* Add CHARMM results with new CaCl_2 model by Claire Loison http://nmrlipids.blogspot.com/2015/12/towards-submission-of-nmrlipids-ii.html?showComment=1463482818700#c8756317300169938071

* Add AvsB figure and update discussion

* Update the discussion

* Update the discussion

* Add bound ions as a function of time from long simulations (delivered by Matti Javanainen through Skype)

* Update LIPIDionINTERACT.tex

Added the DPPC+CaCl2 (Yoo model).
 Not finished yet (bibliography not done, and some other details) !

* Update LIPIDionINTERACT.tex

added references.
to do : add the correlation time for order parameters.

ERROR: I erased in the table two line concerning the other charmm36 simulations.

* Update LIPIDionINTERACT.tex

* Update LIPIDionINTERACT.tex

* Update LIPIDionINTERACT.tex

* Update refs.bib

* Update LIPIDionINTERACT.tex

* Manual merge of CHARMM/yoo model details

* New figures

* Fix typos and add author

* Lot of updates in the manuscript

* Update manuscript

* Add density profiles from Claire Loison, sent by email

* Clarifying the Introduction.

* Small updates

* Update https://github.com/NMRLipids/lipid_ionINTERACTION/commit/0fa2f7fd03e95e718e63ff1b24fbfbfbcae7cd99 to pdf

* details for simulation protocols + small suggestions in introduction/conclusion

* Update text according to discussion in https://github.com/NMRLipids/lipid_ionINTERACTION/pull/29

* Update based on comments in https://github.com/NMRLipids/lipid_ionINTERACTION/issues/30, updates based on small comments by Javanainen through Skype + some other small updates

* Add readme

* Add readme

* Update LIPIDionINTERACT.tex

* Update README

* Update README

* update from NMRlipids orig repo fork (#6)

* Update README

* Update README

* Correction in MS part1 -- up to section C. Cation binding...

* Correction in MS part2 -- up to section III. Conclusions

* Correction in MS part3 -- all corrected, my contributions are yet to be done.

* Correction in MS part4 -- added my contributions (sim details and so). Zenodo links missing still

* added OrdParm and density files for Charmm36_noNBFIX POPC and Slipids DPPC simulation into this branch

* added Zenodo references to my simulations

* Text edits to Molecular electrometer in experiments

* Text edits to Molecular electrometer in experiments

* Text edits to Molecular electrometer in experiments: paragraph 3

* Text edits to Molecular electrometer in experiments: swap paragraphs 2 and 3

* Text edits to Molecular electrometer in experiments: paragraph 4

* Text edits to Molecular electrometer concept in MD simulations: paragraph 1

* Text edits to Molecular electrometer concept in MD simulations: paragraph 2

* Text edits to Molecular electrometer concept in MD simulations: paragraph 3

* Text edits to Molecular electrometer concept in MD simulations: paragraph 4

* Text edits to Molecular electrometer concept in MD simulations: paragraph 5

* Text edits to Molecular electrometer concept in MD simulations: paragraph 6

* Text edits to Cation binding in different simulation models: paragraph 1

* Text edits to Cation binding in different simulation models: paragraphs 2+3

* Text edits to Cation binding in different simulation models: paragraphs 4

* Text edits to Cation binding in different simulation models: paragraph 6

* Text edits to Cation binding in different simulation models: paragraph 7

* Text edits to Conclusions: paragraph 1

* Text edits to Conclusions: paragraph 2

* Text edits to Conclusions: paragraph 3

* Text edits to Conclusions: move paragraph 5 between 2 and 3

* Text edits to Results: move paragraph A4 to B1

* Some comments and changes related to pull request https://github.com/NMRLipids/lipid_ionINTERACTION/pull/33

* Updates

* Final manual merge of pull requests https://github.com/NMRLipids/lipid_ionINTERACTION/pull/33 and https://github.com/NMRLipids/lipid_ionINTERACTION/pull/34

* Clarifications based on comments by Monticelli: http://nmrlipids.blogspot.com/2016/05/towards-submission-of-nmrlipids-ii.html?showComment=1465563106866#c2262591731882451623

* Skype comments by M. Javanainen included

* Skype comments by M. Javanainen included

* Fix https://github.com/NMRLipids/lipid_ionINTERACTION/issues/32

* Update based on comments in https://github.com/NMRLipids/lipid_ionINTERACTION/pull/33

* Small updates

* Update CHARMM36 concentrations without NBFIX as discussed in https://github.com/NMRLipids/lipid_ionINTERACTION/pull/33 and add the results in figures

* Fix Slipid concentrations and update discussion related to the pull request https://github.com/NMRLipids/lipid_ionINTERACTION/pull/33

* Add Slipid 850mM NaCl density profiles

* Clean comments from the manuscript tex

* Small updates

* Change to RSC template

* Updates to the main text

* On AFM.

* On AFM

* Update Supplementary Information text

* On AFM.

* Update pdf

* Small updates

* Textual tuning.

* Textual tuning.

* Textual tuning.

* Removed the claim that AFM would have shown changes in area per lipid.

* Changed millimolar -> sub-molar, as we use it to refer even to [NaCl]>0.1M.

* Change the rest ''millimolar->sub-molar'' according to https://github.com/NMRLipids/lipid_ionINTERACTION/commit/f0a854249931085c0857478916fdc97d743ff58d and small update